root_path : '/Users/cotangentofzero/Data_science/trading_project/'
filepath_input : 'data/raw_data/'
filepath_output : 'data/' 
model_name : "artifacts/trading_model_2"
shift : 9
anomaly_crtiretion : 1.0030
cb_params : {
  'iterations': 300,
  'learning_rate': 0.03,
  'depth': 5,
  'l2_leaf_reg': 2,
  'rsm': 0.7,
  'verbose': False,
  'allow_writing_files': False,
  'random_state': 42
  }
cutoff : 0.04